# Generated by Django 5.1.7 on 2025-04-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_ratecount_profile_servicecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
