# Generated by Django 5.1.7 on 2025-04-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_schedule_phone_alter_schedule_type_of_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='history',
            field=models.BooleanField(default=False),
        ),
    ]
